CREATE TABLE calls (
    ID 					BINARY(16) NOT NULL,
    ROOM_ID             VARCHAR(255) NOT NULL,
    INIT_DEVICE_ID      VARCHAR(255) NULL,
    INIT_DEVICE_START_PRODUCE		TIMESTAMP NULL,
    STATUS              VARCHAR(3) NOT NULL,
    ERROR_CODE          VARCHAR(3) NULL,
    ERROR_REASON        VARCHAR(255) NULL,
    ENTER_RINGING_TIME		TIMESTAMP NULL,
    ENTER_PREVIEW_TIME		TIMESTAMP NULL,
    ENTER_CONVERSATION_TIME	TIMESTAMP NULL,
    ENTER_MISSED_TIME		TIMESTAMP NULL,
    ENTER_FINISHED_TIME		TIMESTAMP NULL,
    IS_AUTOON			BOOLEAN	NOT NULL DEFAULT FALSE,
    IS_MANAGED			BOOLEAN	NOT NULL DEFAULT FALSE,
    CREATION_DATE 		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE 		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_CALL_ROOMS ON calls (ROOM_ID);

CREATE TABLE participants (
    ID 					    BINARY(16) NOT NULL,
    APP_TOKEN               VARCHAR(512) NOT NULL,
    SENT_INVITATION_TIME	TIMESTAMP NULL,
    RINGING_ATTEND_TIME		TIMESTAMP NULL,
    REJECT_TIME             TIMESTAMP NULL,
    PICKUP_TIME		        TIMESTAMP NULL,
    HANGUP_TIME     		TIMESTAMP NULL,
    MANAGE_REQUEST_TIME		TIMESTAMP NULL,
    CALL_ID             BINARY(16) NOT NULL,
    CREATION_DATE 		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE 		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_MOBILE_PATICIPANTS ON participants (APP_TOKEN,CALL_ID);